microservice-chart:
  namespace: "srtp"

  deployment:
    # Keep the IP in sync with the upstream endpoint if it changes.
    hostAliases:
      - ip: "20.31.11.237"
        hostnames:
          - "api-rtp.uat.cstar.pagopa.it"
      - ip: "10.20.0.84"
        hostnames:
          - "cstar-u-itn-srtp-cosmos-account.mongo.cosmos.azure.com"

  image:
    repository: ghcr.io/pagopa/rtp-activator
    tag: snapshot-main
    pullPolicy: Always

  ingress:
    host: "srtp.itn.internal.uat.cstar.pagopa.it"

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "250m"
      memory: "512Mi"

  autoscaling:
    enable: false
#    minReplica: 1
#    maxReplica: 3
#    pollingInterval: 30
#    cooldownPeriod: 300
#    triggers:
#      - type: cpu
#        metadata:
#          type: Utilization
#          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/activation/activations/"
    SP_BASE_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/rtps/"
    EPC_MOCK_URL: "https://api-rtp.uat.cstar.pagopa.it/rtp/mock"
    AZURE_STORAGE_ACCOUNT_NAME: "cstaruitnsrtpsa"
    TAKEOVER_OTP_EXPIRATION: "PT2M"
    TAKEOVER_NOTIFICATION_MAX_CONNECTIONS: "500"
    TAKEOVER_NOTIFICATION_PENDING_QUEUE: "1000"
    TAKEOVER_NOTIFICATION_PENDING_TIMEOUT: "PT45S"

  keyvault:
    name: "cstar-u-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  azureFile:
    create: true
    mounts:
      - shareName: cstar-u-itn-srtp-jks-file-share
        name: share-volume
        readOnly: true

postman-test:
  run: true
  repoName: rtp-activator
  dir: postman
  collectionName: "rtp-activator-E2E.postman_collection.json"
  envVariablesFile: "rtp_uat.postman_environment.json" #inside azdo secure files