microservice-chart:
  namespace: "srtp"

  deployment:
    # Keep the IP in sync with the upstream endpoint if it changes.
    hostAliases:
      - ip: "20.103.162.3"
        hostnames:
          - "api-rtp.cstar.pagopa.it"
      - ip: "10.20.0.4"
        hostnames:
          - "cstar-p-itn-srtp-cosmos-account.mongo.cosmos.azure.com"

  image:
    repository: ghcr.io/pagopa/rtp-activator
    tag: v2.34.0
    pullPolicy: Always

  ingress:
    host: "srtp.itn.internal.cstar.pagopa.it"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 4
    pollingInterval: 30
    cooldownPeriod: 300
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.cstar.pagopa.it/rtp/activation/activations/"
    SP_BASE_URL: "https://api-rtp.cstar.pagopa.it/rtp/rtps/"
    EPC_MOCK_URL: "https://api-rtp.cstar.pagopa.it/rtp/mock"
    AZURE_STORAGE_ACCOUNT_NAME: "cstarpitnsrtpsa"
    TAKEOVER_OTP_EXPIRATION: "PT2M"

  keyvault:
    name: "cstar-p-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  azureFile:
    create: true
    mounts:
      - shareName: cstar-p-itn-srtp-jks-file-share
        name: share-volume
        readOnly: true
