microservice-chart:
  namespace: "srtp"

  deployment:
    # Keep the IP in sync with the upstream endpoint if it changes.
    hostAliases:
      - ip: "20.71.68.43"
        hostnames:
          - "api-mcshared.dev.cstar.pagopa.it"
          - "api-rtp.dev.cstar.pagopa.it"
      - ip: "10.20.0.4"
        hostnames:
          - "cstar-d-itn-srtp-cosmos-account.mongo.cosmos.azure.com"

  image:
    repository: ghcr.io/pagopa/rtp-consumer
    tag: snapshot-main
    pullPolicy: Always


  ingress:
    host: "srtp.itn.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

  autoscaling:
    enable: false
#    minReplica: 1
#    maxReplica: 3
#    pollingInterval: 30 # seconds
#    cooldownPeriod: 300 # seconds
#    triggers:
#      - type: cpu
#        metadata:
#          type: Utilization
#          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.dev.cstar.pagopa.it/rtp/consumer/"
    MIL_AUTH_TOKEN_URL: "https://api-mcshared.dev.cstar.pagopa.it/auth-itn/realms/srtp/protocol/openid-connect/token"
    PROCESS_GPD_MESSAGE_BASE_URL: "https://api-rtp.dev.cstar.pagopa.it/rtp"
    PROCESS_GPD_MESSAGE_TIMEOUT: "PT30S"
    GPD_EVENTHUB_NAME: "pagopa-d-itn-gps-rtp-integration-evh"
    GPD_EVENTHUB_TOPIC: "rtp-events"
    GPD_EVENTHUB_CONSUMER_GROUP: "rtp-events-processor"
    COSMOSDB_RETRY_MAX_ATTEMPTS: "1"
    COSMOSDB_RETRY_BACKOFF_MIN_DURATION: "PT1S"
    COSMOSDB_RETRY_BACKOFF_JITTER: "0.75"
    GPD_MESSAGE_PROCESSING_ENABLED: "true"

  keyvault:
    name: "cstar-d-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
