apiVersion: v2
name: rtp-payees
description: SRTP PAYEES
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 8.6.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"