microservice-chart:
  namespace: "srtp"

  deployment:
    # Keep the IP in sync with the upstream endpoint if it changes.
    hostAliases:
      - ip: "20.103.162.3"
        hostnames:
          - "api-mcshared.cstar.pagopa.it"

  image:
    repository: ghcr.io/pagopa/rtp-consumer
    tag: v1.18.1
    pullPolicy: Always

  ingress:
    host: "srtp.itn.internal.cstar.pagopa.it"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "500m"
      memory: "1Gi"

  autoscaling:
    enable: true
    minReplica: 4
    maxReplica: 6
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "60"

  envConfig:
    PROCESS_GPD_MESSAGE_BASE_URL: "https://api-rtp.cstar.pagopa.it/rtp"
    PROCESS_GPD_MESSAGE_TIMEOUT: "PT30S"
    MIL_AUTH_TOKEN_URL: "https://api-mcshared.cstar.pagopa.it/auth-itn/realms/srtp/protocol/openid-connect/token"
    GPD_EVENTHUB_NAME: "pagopa-p-itn-gps-rtp-integration-evh"
    GPD_EVENTHUB_TOPIC: "rtp-events"
    GPD_EVENTHUB_CONSUMER_GROUP: "rtp-events-processor"
    GPD_MESSAGE_PROCESSING_ENABLED: "true"
    COSMOSDB_RETRY_MAX_ATTEMPTS: "3"
    COSMOSDB_RETRY_BACKOFF_MIN_DURATION: "PT1S"
    COSMOSDB_RETRY_BACKOFF_JITTER: "0.75"

  keyvault:
    name: "cstar-p-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
