parameters:
  - name: params
    type: object
    default: {}

jobs:
  - template: ../k6-tests-template.yml
    parameters:
      ${{ insert }}: ${{ parameters.params }}
      appsList: ['rtp-activator']
      appCategory: 'activation'
      testScript: 'activation-finder.js'
      seedScript: 'create-activations.js'
