microservice-chart:
  namespace: "srtp"

  deployment:
    # Keep the IP in sync with the upstream endpoint if it changes.
    hostAliases:
      - ip: "20.71.68.43"
        hostnames:
          - "api-rtp.dev.cstar.pagopa.it"

  image:
    repository: ghcr.io/pagopa/rtp-payees
    tag: snapshot-main
    pullPolicy: Always


  ingress:
    host: "srtp.itn.internal.dev.cstar.pagopa.it"

  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"
    limits:
      memory: "100Mi"
      cpu: "100m"

  autoscaling:
    enable: false
  #    minReplica: 1
  #    maxReplica: 3
  #    pollingInterval: 30 # seconds
  #    cooldownPeriod: 300 # seconds
  #    triggers:
  #      - type: cpu
  #        metadata:
  #          type: Utilization
  #          value: "60"

  envConfig:
    BASE_URL: "https://api-rtp.dev.cstar.pagopa.it/rtp/payees/"
    BACKOFFICE_BASE_URL: "https://api.uat.platform.pagopa.it/backoffice/pagopa/services/v1"

  keyvault:
    name: "cstar-d-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  # nodeSelector: {}

  # tolerations: []

  # affinity: {}
