apiVersion: v2
name: rtp-sender
description: SRTP SENDER
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: microservice-chart
    version: 8.1.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
