microservice-chart:
  image:
    repository: ghcr.io/pagopa/devops-java-springboot-color
    tag: develop-latest
    pullPolicy: Always

  ingress:
    host: srtp.itn.internal.dev.cstar.pagopa.it

  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "750m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"

  envSecret:
    aks-api-url: cstar-d-itn-dev-aks-apiserver-url

  keyvault:
    name: "cstar-d-itn-srtp-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
